#DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bfriend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ENC(Vli88LkV5vfJDlL4StYMXw==)

    #JPA
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      generate-ddl: false
      properties:
        hibernate:
          show_sql: false
          format_sql: true
          use_sql_comments: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      database: mysql

      #이메일 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(G1kNgTy+v8VD/M6zRJVCdVJ+LCx1hGd4)
    password: ENC(KBLWys7mkKM3UpxGr+nWCNibYvf8RnpWHxpnNwhh6wM=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #Jasypt
  config:
    import: jasypt.yml

sms:
  api:
    key: ENC(ae9vbblwl6e19rRqjJzFsymv6hPG335Qoz8komP40Gk=)
    secretkey: ENC(s5Q72woTJdcYuOKnmZfjpOpYG3OzUyr3PSK7L2Yek0jfDryTchdnD43IvF+/fUCt)
    domain: https://api.coolsms.co.kr

jwt:
  access-token:
    secretkey: ENC(BqjTSmHKi3Rg3/BxFINWV7uJF68DeHvwZoUjr4cxMIB2iW4c8QmpB2RrE6gdQIFPgkgayByy0IhXS86pVrYuDQ==)

#LOG
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
