#DB
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bfriend-mysql.cahtqxbh2c1y.ap-northeast-2.rds.amazonaws.com/bfriend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: frost
    password: ENC(tUFaEtJ5YuR0DFyLk5UdhGP35UyDaLbA)

  redis:
    host: ENC(ALooXJ9NoA96KSzSrtqlPgm/5O1scPJ7OXog0norqPw3Moaen72YGTSqEYBpk5CkOmkJYIwYNMLbLgOz8wh8yAm6vXXmUZgV)
    port: 6379

  #JPA
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

      #이메일 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(G1kNgTy+v8VD/M6zRJVCdVJ+LCx1hGd4)
    password: ENC(KBLWys7mkKM3UpxGr+nWCNibYvf8RnpWHxpnNwhh6wM=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #Jasypt
  config:
    import: jasypt.yml

sms:
  api:
    key: ENC(ae9vbblwl6e19rRqjJzFsymv6hPG335Qoz8komP40Gk=)
    secretkey: ENC(s5Q72woTJdcYuOKnmZfjpOpYG3OzUyr3PSK7L2Yek0jfDryTchdnD43IvF+/fUCt)
    domain: https://api.coolsms.co.kr

jwt:
  access-token:
    secretkey: ENC(BqjTSmHKi3Rg3/BxFINWV7uJF68DeHvwZoUjr4cxMIB2iW4c8QmpB2RrE6gdQIFPgkgayByy0IhXS86pVrYuDQ==)

#LOG
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
